-- Run this in Supabase > SQL Editor.
-- It is safe to run again when updating an existing bheda.me database.
create extension if not exists pgcrypto;

create table if not exists public.posts (
  id uuid primary key default gen_random_uuid(),
  title text not null check (char_length(title) between 1 and 180),
  caption text,
  category text not null default 'Satire',
  media_type text not null check (media_type in ('image','video','embed','text')),
  media_url text,
  embed_url text,
  source_url text,
  author_name text not null default 'Guest sheep',
  created_at timestamptz not null default now()
);

-- Anti-spam metadata. These are server-only and are never displayed in the UI.
alter table public.posts add column if not exists content_fingerprint text;
alter table public.posts add column if not exists publisher_key_hash text;

create table if not exists public.reactions (
  post_id uuid not null references public.posts(id) on delete cascade,
  visitor_id text not null,
  reaction smallint not null check (reaction in (-1,1)),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (post_id, visitor_id)
);

create table if not exists public.comments (
  id uuid primary key default gen_random_uuid(),
  post_id uuid not null references public.posts(id) on delete cascade,
  visitor_id text not null,
  author_name text not null default 'Guest sheep',
  body text not null check (char_length(body) between 1 and 600),
  created_at timestamptz not null default now()
);

-- Persistent rate limiting for Vercel/serverless. Do not replace this with an
-- in-memory counter: serverless instances are short-lived and horizontally scaled.
create table if not exists public.rate_limit_events (
  id bigint generated by default as identity primary key,
  actor_key text not null,
  action text not null,
  created_at timestamptz not null default now()
);

create index if not exists posts_created_at_idx on public.posts(created_at desc);
create index if not exists posts_content_fingerprint_idx on public.posts(content_fingerprint, created_at desc);
create index if not exists reactions_post_id_idx on public.reactions(post_id);
create index if not exists comments_post_id_created_at_idx on public.comments(post_id, created_at desc);
create index if not exists comments_visitor_created_at_idx on public.comments(visitor_id, created_at desc);
create index if not exists rate_limit_actor_action_created_idx on public.rate_limit_events(actor_key, action, created_at desc);
create index if not exists rate_limit_created_at_idx on public.rate_limit_events(created_at);

alter table public.posts enable row level security;
alter table public.reactions enable row level security;
alter table public.comments enable row level security;
alter table public.rate_limit_events enable row level security;

-- Atomic fixed-window-ish limiter. Advisory locking makes concurrent requests for
-- the same actor/action serialize instead of racing past the limit.
create or replace function public.check_rate_limit(
  p_actor_key text,
  p_action text,
  p_limit integer,
  p_window_seconds integer
)
returns table(allowed boolean, retry_after_seconds integer)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_now timestamptz := clock_timestamp();
  v_window_start timestamptz;
  v_count integer;
  v_oldest timestamptz;
begin
  if p_actor_key is null or p_actor_key = '' or p_action is null or p_action = '' then
    raise exception 'actor/action required';
  end if;
  if p_limit < 1 or p_window_seconds < 1 then
    raise exception 'invalid rate limit';
  end if;

  perform pg_advisory_xact_lock(hashtextextended(p_actor_key || ':' || p_action, 0));
  v_window_start := v_now - make_interval(secs => p_window_seconds);

  select count(*), min(created_at)
    into v_count, v_oldest
  from public.rate_limit_events
  where actor_key = p_actor_key
    and action = p_action
    and created_at >= v_window_start;

  if v_count >= p_limit then
    allowed := false;
    retry_after_seconds := greatest(1, ceil(extract(epoch from ((v_oldest + make_interval(secs => p_window_seconds)) - v_now)))::integer);
    return next;
    return;
  end if;

  insert into public.rate_limit_events(actor_key, action, created_at)
  values (p_actor_key, p_action, v_now);

  -- Opportunistic bounded cleanup keeps old abandoned actors from accumulating forever.
  delete from public.rate_limit_events
  where id in (
    select id from public.rate_limit_events
    where created_at < v_now - interval '2 days'
    order by created_at asc
    limit 100
  );

  allowed := true;
  retry_after_seconds := 0;
  return next;
end;
$$;

revoke all on function public.check_rate_limit(text, text, integer, integer) from public, anon, authenticated;
grant execute on function public.check_rate_limit(text, text, integer, integer) to service_role;

-- App database access is intentionally server-only via SUPABASE_SERVICE_ROLE_KEY.
-- No public table policies are required.

insert into storage.buckets (id, name, public)
values ('media', 'media', true)
on conflict (id) do update set public = excluded.public;

-- Storage-level backstop. The API applies a tighter 15 MB limit to images.
update storage.buckets
set file_size_limit = 125829120,
    allowed_mime_types = array['image/jpeg','image/png','image/webp','image/gif','video/mp4','video/webm','video/quicktime']
where id = 'media';
