import type { Post } from "./types";

export const demoPosts: Post[] = [
  {
    id: "demo-1",
    title: "Breaking: productivity app asks you to do the work",
    caption: "Sources close to the situation confirm the button was there the whole time.",
    category: "Hot takes",
    media_type: "image",
    media_url: "https://images.unsplash.com/photo-1499750310107-5fef28a66643?auto=format&fit=crop&w=900&q=82",
    embed_url: null,
    source_url: null,
    author_name: "Bheda desk",
    created_at: new Date(Date.now() - 1000 * 60 * 9).toISOString(),
    likes: 421,
    dislikes: 19,
    score: 402,
    comments_count: 27,
    user_reaction: 0,
  },
  {
    id: "demo-2",
    title: "POV: you said ‘one quick meeting’",
    caption: "Hour two. The agenda has become folklore.",
    category: "Screenshots",
    media_type: "image",
    media_url: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=900&q=82",
    embed_url: null,
    source_url: null,
    author_name: "office sheep",
    created_at: new Date(Date.now() - 1000 * 60 * 28).toISOString(),
    likes: 188,
    dislikes: 8,
    score: 180,
    comments_count: 12,
    user_reaction: 0,
  },
  {
    id: "demo-3",
    title: "Neighborhood café launches $9 emotional support toast",
    caption: "It comes with smashed avocado and one reassuring nod from the barista.",
    category: "Satire",
    media_type: "image",
    media_url: "https://images.unsplash.com/photo-1482049016688-2d3e1b311543?auto=format&fit=crop&w=900&q=82",
    embed_url: null,
    source_url: null,
    author_name: "crumb correspondent",
    created_at: new Date(Date.now() - 1000 * 60 * 48).toISOString(),
    likes: 698,
    dislikes: 34,
    score: 664,
    comments_count: 65,
    user_reaction: 0,
  },
  {
    id: "demo-4",
    title: "A completely serious analysis of group-chat economics",
    caption: "The person who says ‘split evenly’ has ordered three starters.",
    category: "Text",
    media_type: "text",
    media_url: null,
    embed_url: null,
    source_url: null,
    author_name: "budget committee",
    created_at: new Date(Date.now() - 1000 * 60 * 70).toISOString(),
    likes: 251,
    dislikes: 11,
    score: 240,
    comments_count: 31,
    user_reaction: 0,
  },
  {
    id: "demo-5",
    title: "When the weather app says 0% chance of rain",
    caption: "Queensland cloud: challenge accepted.",
    category: "Photos",
    media_type: "image",
    media_url: "https://images.unsplash.com/photo-1501691223387-dd0500403074?auto=format&fit=crop&w=900&q=82",
    embed_url: null,
    source_url: null,
    author_name: "forecast department",
    created_at: new Date(Date.now() - 1000 * 60 * 100).toISOString(),
    likes: 329,
    dislikes: 6,
    score: 323,
    comments_count: 17,
    user_reaction: 0,
  },
  {
    id: "demo-6",
    title: "Internet archaeology: cable drawer, circa 2014",
    caption: "Every cable is apparently too important to throw away and too old to identify.",
    category: "Internet archaeology",
    media_type: "image",
    media_url: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=900&q=82",
    embed_url: null,
    source_url: null,
    author_name: "museum of tabs",
    created_at: new Date(Date.now() - 1000 * 60 * 160).toISOString(),
    likes: 877,
    dislikes: 23,
    score: 854,
    comments_count: 104,
    user_reaction: 0,
  },
  {
    id: "demo-7",
    title: "Tiny plant survives entirely on guilt and one cup of water",
    caption: "Experts are calling it resilient. The plant declined to comment.",
    category: "Photos",
    media_type: "image",
    media_url: "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?auto=format&fit=crop&w=900&q=82",
    embed_url: null,
    source_url: null,
    author_name: "indoor jungle bureau",
    created_at: new Date(Date.now() - 1000 * 60 * 210).toISOString(),
    likes: 540,
    dislikes: 13,
    score: 527,
    comments_count: 42,
    user_reaction: 0,
  },
  {
    id: "demo-8",
    title: "Weekend plan upgraded from ambitious to horizontal",
    caption: "A lifestyle pivot with strong stakeholder support.",
    category: "Satire",
    media_type: "image",
    media_url: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=900&q=82",
    embed_url: null,
    source_url: null,
    author_name: "strategic resting unit",
    created_at: new Date(Date.now() - 1000 * 60 * 280).toISOString(),
    likes: 764,
    dislikes: 29,
    score: 735,
    comments_count: 88,
    user_reaction: 0,
  }
];
